CREATE TABLE IF NOT EXISTS blog_posts (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    excerpt VARCHAR(500) NULL,
    body LONGTEXT NOT NULL,
    cover_image VARCHAR(500) NULL,
    status ENUM('draft', 'published') NOT NULL DEFAULT 'draft',
    author_id INT UNSIGNED NOT NULL,
    category_id INT UNSIGNED NULL,
    published_date DATETIME NULL,
    views INT UNSIGNED NOT NULL DEFAULT 0,
    seo_title VARCHAR(255) NULL,
    seo_description VARCHAR(500) NULL,
    deleted_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_blog_posts_status (status),
    INDEX idx_blog_posts_category (category_id),
    INDEX idx_blog_posts_author (author_id),
    INDEX idx_blog_posts_published_date (published_date),
    CONSTRAINT fk_blog_posts_author FOREIGN KEY (author_id) REFERENCES blog_users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_blog_posts_category FOREIGN KEY (category_id) REFERENCES blog_categories (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
